'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Woory tools",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import { Providers } from './provider';

import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';  // DatePicker를 사용하는 경우
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  if (typeof window !== 'undefined') {
  const originalToJSON = Date.prototype.toJSON;
  Date.prototype.toJSON = function() {
    return this.toLocaleString('ko-KR');
  };
}
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}